name: CollatClient

on:
  push:
  pull_request:

jobs:
  lint-test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./collatClient

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - run: npm ci
    - run: npm run checklint
    - run: npm test
